#1 step one

In [1]:
import pandas as pd
import os

In [2]:
file_path = "C:\\Users\\Raja\\OneDrive\\Desktop\\cafe_data_cleaning\\data\\raw\\cafe_sales_dirty.csv"
df =pd.read_csv(file_path)

In [9]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 1.1 MB

In [7]:
df.head(10000)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [10]:
df.replace(['error', 'null', 'unknown','', 'missing'], pd.NA, inplace=True)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [11]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [13]:

df.replace(['ERROR', 'UNKNOWN', ''], pd.NA, inplace=True)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [14]:
df.isnull().sum().sum()

np.int64(10082)

In [15]:
df[df.isnull().any(axis=1)]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,NaN,3,3.0,9.0,NaN,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,NaN,2023-10-28
...,...,...,...,...,...,...,...,...
9994,TXN_7851634,NaN,4,4.0,16.0,NaN,NaN,2023-01-08
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02

In [16]:
for col in df.select_dtypes(include=['object', 'string']).columns:
    print(col)
    print(df[col].unique())
    print()

Transaction ID
<ArrowStringArray>
['TXN_1961373', 'TXN_4977031', 'TXN_4271903', 'TXN_7034554', 'TXN_3160411',
 'TXN_2602893', 'TXN_4433211', 'TXN_6699534', 'TXN_4717867', 'TXN_2064365',
 ...
 'TXN_1538510', 'TXN_3897619', 'TXN_2739140', 'TXN_4766549', 'TXN_7851634',
 'TXN_7672686', 'TXN_9659401', 'TXN_5255387', 'TXN_7695629', 'TXN_6170729']
Length: 10000, dtype: str

Item
<ArrowStringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',        nan,
 'Sandwich',    'Juice',      'Tea']
Length: 9, dtype: str

Quantity
<ArrowStringArray>
['2', '4', '5', '3', '1', nan]
Length: 6, dtype: str

Price Per Unit
<ArrowStringArray>
['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan]
Length: 7, dtype: str

Total Spent
<ArrowStringArray>
[ '4.0', '12.0',    nan, '10.0', '20.0',  '9.0', '16.0', '15.0', '25.0',
  '8.0',  '5.0',  '3.0',  '6.0',  '2.0',  '1.0',  '7.5',  '4.5',  '1.5']
Length: 18, dtype: str

Payment Method
<ArrowStringArray>
['Credit Card', 'Cash', nan, 'Digital Wallet']
Length: 4, dtype: str

Location
<ArrowStringArray>
['Takeaway', 'In-store', nan]
Length: 3, dtype: str

Transaction Date
<ArrowStringArray>
[ '2023-09-08',  '2023-05-16',  '2023-07-19',  '2023-04-27',  '2023-06-11',
 '2023-03-31 ',  '2023-10-06',  '2023-10-28',  '2023-07-28',  '2023-12-31',
 ...
  '2023-08-01',  '2023-01-20',  '2023-11-11',  '2023-02-13',  '2023-07-30',
  '2023-02-17',  '2023-05-20',  '2023-11-05',  '2023-03-27',  '2023-07-03']
Length: 367, dtype: str

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.dtypes

Transaction ID      str
Item                str
Quantity            str
Price Per Unit      str
Total Spent         str
Payment Method      str
Location            str
Transaction Date    str
dtype: object

In [19]:
numeric_cols = ['Quantity', 'Price Per Unit', 'Total Spent']

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [20]:
df.dtypes

Transaction ID          str
Item                    str
Quantity            float64
Price Per Unit      float64
Total Spent         float64
Payment Method          str
Location                str
Transaction Date        str
dtype: object

In [21]:
df['Transaction Date'] = pd.to_datetime(
    df['Transaction Date'],
    errors='coerce'
)

In [22]:
df.dtypes

Transaction ID                 str
Item                           str
Quantity                   float64
Price Per Unit             float64
Total Spent                float64
Payment Method                 str
Location                       str
Transaction Date    datetime64[us]
dtype: object

In [23]:
numeric_cols = ['Quantity', 'Price Per Unit', 'Total Spent']

for col in numeric_cols:
    df[col].fillna(df[col].median(), inplace=True)

C:\Users\Raja\AppData\Local\Temp\ipykernel_2824\3725819257.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\Raja\AppData\Local\Temp\ipykernel_2824\3725819257.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\Raja\AppData\Local\Temp\ipykernel_2824\3725819257.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)

In [24]:
df[col] = df[col].fillna(df[col].median())

In [25]:
numeric_cols = ['Quantity', 'Price Per Unit', 'Total Spent']

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

In [26]:
categorical_cols = ['Item', 'Payment Method', 'Location']

for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

In [27]:
df.isnull().sum().sum()

np.int64(461)

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df['Calculated Total'] = df['Quantity'] * df['Price Per Unit']

In [30]:
wrong_rows = df[df['Calculated Total'] != df['Total Spent']]

print(wrong_rows)

     Transaction ID      Item  Quantity  Price Per Unit  Total Spent  \
2       TXN_4271903    Cookie       4.0             1.0          8.0
20      TXN_3522028  Smoothie       3.0             4.0         20.0
25      TXN_7958992  Smoothie       3.0             4.0          8.0
31      TXN_8927252     Juice       2.0             1.0          8.0
42      TXN_6650263       Tea       2.0             1.5          8.0
...             ...       ...       ...             ...          ...
9977    TXN_5548914     Juice       2.0             3.0          8.0
9984    TXN_3142496  Smoothie       3.0             4.0          4.0
9988    TXN_9594133      Cake       5.0             3.0          8.0
9996    TXN_9659401     Juice       3.0             3.0          3.0
9998    TXN_7695629    Cookie       3.0             3.0          3.0

      Payment Method  Location Transaction Date  Calculated Total
2        Credit Card  In-store       2023-07-19               4.0
20              Cash  In-store       2023-04-04              12.0
25    Digital Wallet  Takeaway       2023-12-13              12.0
31       Credit Card  Takeaway       2023-11-06               2.0
42    Digital Wallet  Takeaway       2023-01-10               3.0
...              ...       ...              ...               ...
9977  Digital Wallet  In-store       2023-11-04               6.0
9984            Cash  Takeaway       2023-07-27              12.0
9988  Digital Wallet  Takeaway              NaT              15.0
9996  Digital Wallet  Takeaway       2023-06-02               9.0
9998  Digital Wallet  Takeaway       2023-12-02               9.0

[1194 rows x 9 columns]

#Feature Engineering

In [31]:
df['Day of Week'] = df['Transaction Date'].dt.day_name()

In [32]:
df['Month'] = df['Transaction Date'].dt.month_name()

In [33]:
df['Year'] = df['Transaction Date'].dt.year

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              10000 non-null  str
 2   Quantity          10000 non-null  float64
 3   Price Per Unit    10000 non-null  float64
 4   Total Spent       10000 non-null  float64
 5   Payment Method    10000 non-null  str
 6   Location          10000 non-null  str
 7   Transaction Date  9539 non-null   datetime64[us]
 8   Calculated Total  10000 non-null  float64
 9   Day of Week       9539 non-null   str
 10  Month             9539 non-null   str
 11  Year              9539 non-null   float64
dtypes: datetime64[us](1), float64(5), str(6)
memory usage: 1.4 MB

In [35]:
df.describe()

,Quantity,Price Per Unit,Total Spent,Transaction Date,Calculated Total,Year
count,10000.000000,10000.00000,10000.00000,9539,10000.000000,9539.0
mean,3.027100,2.95265,8.87795,2023-07-01 23:14:33.676486,8.948150,2023.0
min,1.000000,1.00000,1.00000,2023-01-01 00:00:00,1.000000,2023.0
25%,2.000000,2.00000,4.00000,2023-04-01 00:00:00,4.000000,2023.0
50%,3.000000,3.00000,8.00000,2023-07-02 00:00:00,8.000000,2023.0
75%,4.000000,4.00000,12.00000,2023-10-02 00:00:00,12.000000,2023.0
max,5.000000,5.00000,25.00000,2023-12-31 00:00:00,25.000000,2023.0
std,1.384614,1.24396,5.86059,NaN,5.831191,0.0

In [36]:
df.isnull().sum()

Transaction ID        0
Item                  0
Quantity              0
Price Per Unit        0
Total Spent           0
Payment Method        0
Location              0
Transaction Date    461
Calculated Total      0
Day of Week         461
Month               461
Year                461
dtype: int64

In [37]:
df.dropna(subset=['Transaction Date'], inplace=True)

In [38]:
df['Day of Week'] = df['Transaction Date'].dt.day_name()

In [39]:
df.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
Calculated Total    0
Day of Week         0
Month               0
Year                0
dtype: int64

In [40]:
df.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Calculated Total,Day of Week,Month,Year
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,4.0,Friday,September,2023.0
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,12.0,Tuesday,May,2023.0
2,TXN_4271903,Cookie,4.0,1.0,8.0,Credit Card,In-store,2023-07-19,4.0,Wednesday,July,2023.0
3,TXN_7034554,Salad,2.0,5.0,10.0,Digital Wallet,Takeaway,2023-04-27,10.0,Thursday,April,2023.0
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,4.0,Sunday,June,2023.0
6,TXN_4433211,Juice,3.0,3.0,9.0,Digital Wallet,Takeaway,2023-10-06,9.0,Friday,October,2023.0
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,Takeaway,2023-10-28,16.0,Saturday,October,2023.0
8,TXN_4717867,Juice,5.0,3.0,15.0,Digital Wallet,Takeaway,2023-07-28,15.0,Friday,July,2023.0
9,TXN_2064365,Sandwich,5.0,4.0,20.0,Digital Wallet,In-store,2023-12-31,20.0,Sunday,December,2023.0
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07,25.0,Tuesday,November,2023.0

In [41]:
df.info()

<class 'pandas.DataFrame'>
Index: 9539 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    9539 non-null   str
 1   Item              9539 non-null   str
 2   Quantity          9539 non-null   float64
 3   Price Per Unit    9539 non-null   float64
 4   Total Spent       9539 non-null   float64
 5   Payment Method    9539 non-null   str
 6   Location          9539 non-null   str
 7   Transaction Date  9539 non-null   datetime64[us]
 8   Calculated Total  9539 non-null   float64
 9   Day of Week       9539 non-null   str
 10  Month             9539 non-null   str
 11  Year              9539 non-null   float64
dtypes: datetime64[us](1), float64(5), str(6)
memory usage: 1.4 MB

In [42]:
df.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
Calculated Total    0
Day of Week         0
Month               0
Year                0
dtype: int64

In [43]:
df.shape

(9539, 12)

In [44]:
df['Item'].value_counts()

Item
Juice       2051
Coffee      1123
Salad       1099
Cake        1082
Sandwich    1075
Smoothie    1047
Cookie      1035
Tea         1027
Name: count, dtype: int64

In [45]:
df.groupby('Item')['Total Spent'].sum()

Item
Cake         9777.0
Coffee       6922.0
Cookie       3346.0
Juice       18087.0
Salad       16263.0
Sandwich    12824.0
Smoothie    12556.0
Tea          4813.5
Name: Total Spent, dtype: float64

In [46]:
df['Payment Method'].value_counts()

Payment Method
Digital Wallet    5212
Credit Card       2169
Cash              2158
Name: count, dtype: int64

In [47]:
df.groupby('Location')['Total Spent'].sum()

Location
In-store    25794.0
Takeaway    58794.5
Name: Total Spent, dtype: float64

In [48]:
df.groupby('Month')['Total Spent'].sum()

Month
April        7138.5
August       7112.0
December     7097.0
February     6584.0
January      7221.0
July         6910.0
June         7327.5
March        7178.0
May          6970.0
November     6884.5
October      7336.5
September    6829.5
Name: Total Spent, dtype: float64

In [49]:
df.groupby('Day of Week')['Total Spent'].sum()

Day of Week
Friday       12244.0
Monday       12161.5
Saturday     11976.0
Sunday       12246.5
Thursday     12362.5
Tuesday      11957.0
Wednesday    11641.0
Name: Total Spent, dtype: float64

In [50]:
original_rows = 10000
cleaned_rows = df.shape[0]

print("Removed rows:", original_rows - cleaned_rows)

Removed rows: 461

In [53]:
df.to_csv('C:\\Users\\Raja\\OneDrive\\Desktop\\cafe_data_cleaning\\data\\processed\\cafe_sales_cleaned.csv', index=False)